import { v4 as uuidv4 } from 'uuid';
import { getNextOSId } from './osIdService';
import { formatDateForBackend } from '@/utils/dateUtils';

export const initialServicoM2State = () => ({
  id_item_os: uuidv4(),
  tipo_item: 'm2',
  produto_id: null,
  nome_servico_produto: '',
  altura: '',
  largura: '',
  area_calculada_item: 0,
  quantidade: '1',
  valor_unitario_m2: '0.00',
  valor_unitario_bloqueado: false,
  valor_produto_origem: '',
  acabamentos_selecionados: [],
  subtotal_acabamentos: 0,
  subtotal_item: 0,
  detalhes: '',
  imagem_url: '',
  consumo_material_utilizado: '',
  consumo_largura_peca: '',
  consumo_altura_peca: '',
  consumo_quantidade_solicitada: '',
  consumo_largura_chapa: '',
  consumo_altura_chapa: '',
  consumo_valor_unitario_chapa: '',
  consumo_pecas_por_chapa: 0,
  consumo_chapas_necessarias: 0,
  consumo_custo_total: 0,
  consumo_custo_unitario: 0,
  consumo_aproveitamento_percentual: 0,
});

export const initialProdutoUnidadeState = () => ({
  id_item_os: uuidv4(),
  tipo_item: 'unidade',
  produto_id: null,
  nome_produto: '',
  quantidade: '1',
  valor_unitario: '0.00',
  valor_unitario_bloqueado: false,
  valor_produto_origem: '',
  subtotal_item: 0,
  detalhes: '',
  imagem_url: '',
  variacao_selecionada: null,
});

// Versão síncrona para casos onde não precisamos do ID sequencial
export const initialOrdemServicoStateSync = () => ({
  id_os: `OS-${Date.now()}-${uuidv4().slice(0,4)}`,
  numero_os: 0,
  cliente_id: null,
  cliente_info: null,
  cliente_nome_manual: '',
  vendedor_id: null,
  vendedor_nome: '',
  data_criacao: formatDateForBackend(),
  data_previsao_entrega: '',
  status_os: 'Orçamento Salvo',
  status_pagamento: 'Pendente',
  itens: [],
  subtotal_servicos_produtos: 0,
  subtotal_acabamentos_geral: 0,
  valor_entrada: '0.00',
  desconto_terceirizado_percentual: '0',
  desconto_geral_tipo: 'percentual',
  desconto_geral_valor: '0',
  frete_valor: '0',
  valor_total_os: 0,
  observacoes_gerais_os: '',
  observacoes_cliente_para_nota: '',
  termos_condicoes: 'Termos e condições padrão da empresa.',
  assinatura_cliente_url: '',
  data_finalizacao_os: null,
  data_ultima_modificacao: formatDateForBackend(),
  forma_pagamento_principal: null,
  pagamentos: [],
  local_entrega: null,
  custo_total_estimado_produtos: 0,
  custo_total_estimado_acabamentos: 0,
  custo_total_estimado_servicos_m2: 0,
  margem_lucro_total_estimada: 0,
  comissao_total_os: 0,
  foi_orcamento: true, 
  data_aprovacao_orcamento: null,
  data_entrega_realizada: null,
  quem_retirou: '',
  documento_quem_retirou: '',
  nota_fiscal_path: '',
  arte_final_path: '',
  isEditandoViaHistorico: false,
  funcionario_consumidor_id: null,
  maquina_impressao_id: null,
});

// Versão assíncrona para gerar ID sequencial
export const initialOrdemServicoState = async () => {
  const proximoId = await getNextOSId();
  return {
    id_os: `OS-${proximoId}`,
    numero_os: proximoId,
    cliente_id: null,
    cliente_info: null,
    cliente_nome_manual: '',
    vendedor_id: null,
    vendedor_nome: '',
    data_criacao: formatDateForBackend(),
    data_previsao_entrega: '',
    status_os: 'Orçamento Salvo',
    status_pagamento: 'Pendente',
    itens: [],
    subtotal_servicos_produtos: 0,
    subtotal_acabamentos_geral: 0,
    valor_entrada: '0.00',
    desconto_terceirizado_percentual: '0',
    desconto_geral_tipo: 'percentual',
    desconto_geral_valor: '0',
    frete_valor: '0',
    valor_total_os: 0,
    observacoes_gerais_os: '',
    observacoes_cliente_para_nota: '',
    termos_condicoes: 'Termos e condições padrão da empresa.',
    assinatura_cliente_url: '',
    data_finalizacao_os: null,
    data_ultima_modificacao: formatDateForBackend(),
    forma_pagamento_principal: null,
    pagamentos: [],
    local_entrega: null,
    custo_total_estimado_produtos: 0,
    custo_total_estimado_acabamentos: 0,
    custo_total_estimado_servicos_m2: 0,
    margem_lucro_total_estimada: 0,
    comissao_total_os: 0,
    foi_orcamento: true, 
    data_aprovacao_orcamento: null,
    data_entrega_realizada: null,
    quem_retirou: '',
    documento_quem_retirou: '',
    nota_fiscal_path: '',
    arte_final_path: '',
    isEditandoViaHistorico: false,
    funcionario_consumidor_id: null,
    maquina_impressao_id: null,
  };
};

export const ACABAMENTOS_DEFAULT = [
  { 
    id: 'acab1', 
    nome_acabamento: 'LAMINAÇÃO 1,22 - R$ 24.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '24.00', 
    valor_un: '0.00', 
    observacoes: '', 
    custo_m2: '5.00', 
    custo_un: '0.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#90EE90',
  },
  { 
    id: 'acab2', 
    nome_acabamento: 'IMPRESSÃO ECO-SOLVENTE - R$ 50.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '50.00', 
    valor_un: '0.00', 
    observacoes: '', 
    custo_m2: '4.00', 
    custo_un: '0.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#32CD32',
  },
  { 
    id: 'acab3', 
    nome_acabamento: 'LAMINAÇÃO COM VINIL DE JATEADO 1,22 - R$ 24.73/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '24.73', 
    valor_un: '0.00', 
    observacoes: '', 
    custo_m2: '0.00', 
    custo_un: '0.50',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#FFB6C1',
  },
  { 
    id: 'acab4', 
    nome_acabamento: 'RECORTE ELETRONICO - R$ 15.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '15.00', 
    valor_un: '0.00', 
    observacoes: 'Para banners', 
    custo_m2: '0.00', 
    custo_un: '2.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#FFA500',
  },
  { 
    id: 'acab5', 
    nome_acabamento: 'ACABAMENTO PARA BANNER - R$ 10.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '10.00', 
    valor_un: '0.00', 
    observacoes: 'Para adesivos com formatos complexos', 
    custo_m2: '3.00', 
    custo_un: '0.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#FFE4B5',
  },
  { 
    id: 'acab6', 
    nome_acabamento: 'APLICAÇÃO - R$ 30.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '30.00', 
    valor_un: '0.00', 
    observacoes: '', 
    custo_m2: '3.00', 
    custo_un: '0.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#87CEEB',
  },
  { 
    id: 'acab7', 
    nome_acabamento: 'GRAVAÇÃO A LASER - R$ 100.00/m²', 
    tipo_aplicacao: 'area_total', 
    valor_m2: '100.00', 
    valor_un: '0.00', 
    observacoes: '', 
    custo_m2: '3.00', 
    custo_un: '0.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#DDA0DD',
  },
  { 
    id: 'acab8', 
    nome_acabamento: 'ESTRUTURA DE METALON - R$ 55.00/un', 
    tipo_aplicacao: 'unidade', 
    valor_m2: '0.00', 
    valor_un: '55.00', 
    observacoes: '', 
    custo_m2: '0.00', 
    custo_un: '2.00',
    ativo: true,
    produto_vinculado_id: null,
    produto_vinculado_nome: '',
    produto_vinculado_custo: '0.00',
    produto_vinculado_unidade_medida: '',
    produto_vinculado_estoque_no_momento_do_cadastro: 0,
    quantidade_produto_por_unidade_acabamento: '1',
    cor_fundo: '#F5F5F5',
  },
];